---
title: "R Notebook"
output: html_notebook
---

```{r}
library(plotly)
library(tidyverse)
library(caret)
library(factoextra)
library(dbscan)
library(xml2)
```

```{r}
x <- read_xml("orlando.nod.xml")

xml_children(x)
nodes <- xml_find_all(x, ".//node")
typeof(nodes)

df <- data.frame(id= xml_attr(nodes, "id"), x=as.numeric(xml_attr(nodes, "x")), y=as.numeric(xml_attr(nodes, "y"))) %>% select(c(x, y))

```
```{r}
stand_params <- preProcess(df, method=c("center", "scale"))
transform_stand <- predict(stand_params, df)
transform_stand

ggplot(transform_stand, aes(x=x, y=y)) + geom_point()

```

```{r}


fviz_nbclust(transform_stand, kmeans, method="wss")
fviz_nbclust(transform_stand, hcut, method="wss")

```
```{r}
km <- kmeans(transform_stand, 20)
fviz_cluster(km, transform_stand, geom="point") 
```
```{r}
hcl <- hclust(dist(transform_stand), method="ward.D") #average,d looks good
hcl_result <- as.factor(cutree(hcl, 20))

ggplot(df, aes(x=x, y=y, color=hcl_result)) + geom_point()
```
```{r}
dbr <- dbscan(transform_stand, eps = 0.1, minPts = 2)

fviz_cluster(dbr, transform_stand, geom="point") 

```

```{r}
df %>% mutate(cluster = km$cluster)# %>%  write.csv("points.csv")
```
```{r}
for(i in unique(df))


```

